import type React from "react"
import "./globals.css"
import { Inter } from "next/font/google"
import Script from "next/script" // Import Script

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* UTMify Pixel Script */}
        <Script id="utmify-pixel-script" strategy="afterInteractive">
          {`
            window.pixelId = "6888622de8486a4fa48fe7cb";
            var a = document.createElement("script");
            a.setAttribute("async", "");
            a.setAttribute("defer", "");
            a.setAttribute("src", "https://cdn.utmify.com.br/scripts/pixel/pixel.js");
            document.head.appendChild(a);
          `}
        </Script>
        {/* UTMify UTMS Script */}
        <Script
          src="https://cdn.utmify.com.br/scripts/utms/latest.js"
          data-utmify-prevent-xcod-sck
          data-utmify-prevent-subids
          async
          defer
          strategy="afterInteractive" // Recommended strategy for third-party scripts
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
